language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: precise

before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10 #increment timeout to 20 mins

android:
  components:
    # tools required
    - tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-22
    - android-28

script:
  - cd ..
  - git clone https://github.com/OpenSRP/opensrp-client-native-form.git
  - cd opensrp-client-native-form
  - git checkout fix-repeating-group-feature
  - cd ../opensrp-client-maternity
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  # jacocoTestReport is supposed to run both local and instrumented tests on all the modules
  # Gradle issue running composite tasks in order https://github.com/gradle/gradle/issues/3300
  - travis_wait ./gradlew clean --stacktrace
  - travis_wait ./gradlew build --stacktrace
  - travis_wait ./gradlew :opensrp-maternity:jacocoTestReport --stacktrace
  - travis_wait ./gradlew :opensrp-maternity:coveralls

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=
