---
group:
sub_group: pregnancy_data
fields:
  - template: "Intake Time: {intake_time}"
    relevance: "intake_time != ''"

  - template: "Gravida: {gravidity}"
    relevance: "gravidity != ''"

  - template: "Para: {parity}"
    relevance: "parity != ''"

  - template: "Gestation Week: {gestation_week}"
    relevance: "gestation_week != ''"

---
sub_group: hiv_details
fields:
  - template: "Status: {hiv_status}"
    relevance: "hiv_status != ''"
    isRedFont: "hiv_status == 'positive' || hiv_status == 'Positive'"